### ISSUE TITLE
Do you have any open source plans for the Stage II in your latest paper?

### ISSUE THREAD

**Issue by seacj** [TaoRuijie/ECAPA-TDNN#20]
I have read your great work in SELF-SUPERVISED SPEAKER RECOGNITION WITH LOSS-GATED LEARNING（ICASSP 2022). 

I attempt to follow Stage II in your paper, which shows great gains in your experiments.  

If these parts of codes are available, it will benefit a lot. 

Thanks a lot.

**Comment by TaoRuijie** [comment]
Thanks for your interest, I plan to release the code later (maybe on May or June) since I am doing other works recently.

**Comment by seacj** [comment]
Thx
