### ISSUE TITLE
pip install -r requirements.txt 出错

### ISSUE THREAD

**Issue by wtl-lang** [TaoRuijie/ECAPA-TDNN#25]
ERROR: Invalid requirement: 'torch==1.7.1+cu110 torchvision==0.8.2+cu110 torchaudio==0.7.2' (from line 1 of requirements.txt)

**Comment by TaoRuijie** [comment]
pip3 install torch==1.10.2+cu113 torchvision==0.11.3+cu113 torchaudio==0.10.2+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html

**Comment by wtl-lang** [comment]
ok, 3q
