### ISSUE TITLE
关于AS-norm的问题，

### ISSUE THREAD

**Issue by ikou-austin** [TaoRuijie/ECAPA-TDNN#26]
Hi！Ruijie，在B站关注你好久了！最近在做SASVC的比赛，发现用了你这个仓库做ASV  的 Baseline code. 你在Readme中写了这个ECAPA-TDNN结果是as-norm后的结果，可我没有在你的代码里找到任何关于backend norm的部分。请问是typo吗？还是您没有向本仓库中添加那一段代码?

**Comment by TaoRuijie** [comment]
你好，不是的，请看readme这一段：

```
With AS-norm, this system performs EER: 0.86. We will not update this code recently since no enough time for this work. I suggest you the following paper if you want to add AS-norm or other norm methods:

Matejka, Pavel, et al. "Analysis of Score Normalization in Multilingual Speaker Recognition." INTERSPEECH. 2017.
```

就是我写的不满意，所以暂时我没有提供这块代码的打算。如果想加上去参考提供的ref，我当时参考这个写的感觉写上去还是比较容易的。

**Comment by ikou-austin** [comment]
好的，感谢回复！

**Comment by JJ-Guo1996** [comment]
> Hi！Ruijie，在B站关注你好久了！最近在做SASVC的比赛，发现用了你这个仓库做ASV 的 Baseline code. 你在Readme中写了这个ECAPA-TDNN结果是as-norm后的结果，可我没有在你的代码里找到任何关于backend norm的部分。请问是typo吗？还是您没有向本仓库中添加那一段代码?

请问你现在有尝试AS-norm策略吗？效果如何呢？我用了效果并不好呢
