### ISSUE TITLE
GPU utilization error！

### ISSUE THREAD

**Issue by daiyuuu** [TaoRuijie/ECAPA-TDNN#27]
Hi, author. I am training the ECAPA-TDNN model end-to-end by using: python trainECAPAModel.py 
However, I found that while training, the training time per epoch is very long. After checking, I found that the GPU memory is occupied, but its utilization is 0. I manually set model.cuda(), but it does not work. I'm wondering what part of the program should I change to make the model load successfully.

**Comment by TaoRuijie** [comment]
Please check this:

https://github.com/TaoRuijie/ECAPA-TDNN/issues/7

**Comment by daiyuuu** [comment]
Got it, thank you very much
