### ISSUE TITLE
How to speed up training?

### ISSUE THREAD

**Issue by Drawlone** [TaoRuijie/ECAPA-TDNN#29]
My GPU is also RTX 3090. Why is your training speed so fast? Mine is about 6 times slower!

**Comment by TaoRuijie** [comment]
use nvidia-smi to check the status of your GPU to make sure your GPU is running in the full speed. Which means GPU-Util is almost 100%

**Comment by underdogliu** [comment]
Yes I have got same problem on the runner. It roughly takes 2~2.5 seconds per-loop for 80-mel filterbank input. I'd like to ask if there is distributed setups or @TaoRuijie you used one TITAN X GPU from the beginning to the end.

**Comment by TaoRuijie** [comment]
No distributed steps, I only use one 3090 GPU from the beginning to the end.

**Comment by Drawlone** [comment]
看了您在blibili的[为什么训练时GPU使用率低，跑的这么慢？磕盐经验分享](https://www.bilibili.com/video/BV1dF411g7t1?share_source=copy_web)，我已经找出了问题所在，感谢分享，受益良多！

**Comment by jindongfu8-ui** [comment]
你好，能问一下具体是怎样解决的吗？
