### ISSUE TITLE
算法正确率并不高？

### ISSUE THREAD

**Issue by JJ-Guo1996** [TaoRuijie/ECAPA-TDNN#39]
80 epoch, LR 0.000090, LOSS 1.371865, ACC 74.04%, EER 1.03%, bestEER 0.96%
看到训练log，在第80个epoch的时候，eer已经达到1.03，但是ACC却只有74.04，正确率并不高呢？

**Comment by TaoRuijie** [comment]
请查看aamsoftmax算法和softmax算法的不同
