### ISSUE TITLE
AS-Norm

### ISSUE THREAD

**Issue by miao-123-456** [TaoRuijie/ECAPA-TDNN#42]
Has anyone implemented as-norm? Can you share it with me?
thank you very much！！

**Comment by JJ-Guo1996** [comment]
> Has anyone implemented as-norm? Can you share it with me? thank you very much！！

Hi，do you try the AS-norm? and how about the performance ?

**Comment by miao-123-456** [comment]
> > 有没有人按照规范实施？你能和我分享吗？非常感谢您！！
> 
> 你好，你试过AS-norm吗？表现如何？
I'd love to try, but I don't know how to add this part.

**Comment by JJ-Guo1996** [comment]
> > > 有没有人按照规范实施？你能和我分享吗？非常感谢您！！
> > 
> > 
> > 你好，你试过AS-norm吗？表现如何？
> > I'd love to try, but I don't know how to add this part.
I do it ,but the performance is poor, the EER is about 2

**Comment by miao-123-456** [comment]
> > > > 有没有人按照规范实施？你能和我分享吗？非常感谢您！！
> > > 
> > > 
> > > 你好，你试过AS-norm吗？表现如何？
> > > I'd love to try, but I don't know how to add this part.
> > > I do it ,but the performance is poor, the EER is about 2
Can you share the code to me? I can try training and share with you if I have good results.
