### ISSUE TITLE
Online augmentation affects speed

### ISSUE THREAD

**Issue by IStar-Lee** [TaoRuijie/ECAPA-TDNN#43]
Hello, when I'm training, I find that data augmentation always waste a lot of time which cause the gpu (3090) to run intermittently. There are almost 20 seconds used for augmentation every batch(batch_size = 400). I want to ask you why yours so fast. Looking forward to your reply.

**Comment by TaoRuijie** [comment]
You may can check this video. https://www.bilibili.com/video/BV1dF411g7t1/
