### ISSUE TITLE
EER 15%?

### ISSUE THREAD

**Issue by rlaehgud7942** [TaoRuijie/ECAPA-TDNN#46]
![image](https://user-images.githubusercontent.com/53420362/200789687-92842427-d6ee-44cd-a237-dc40f7258ec2.png)
I got EER:15.98% with pretrain.model and Vox1_O(https://www.robots.ox.ac.uk/~vgg/data/voxceleb/meta/veri_test2.txt)
Is it right?
![image](https://user-images.githubusercontent.com/53420362/200789859-4838c5f6-1689-4446-8d8c-4d8c8926fe18.png)

**Comment by TaoRuijie** [comment]
It looks wrong...

**Comment by rlaehgud7942** [comment]
How long do you think it will take to train this model using the 3070?
