### ISSUE TITLE
单卡改多卡

### ISSUE THREAD

**Issue by JJun-Guo** [TaoRuijie/ECAPA-TDNN#47]
请问尝试过将代码改成多卡吗？我这边改完之后，收敛速度很慢。
89 epoch, LR 0.000069, LOSS 2.890798, ACC 48.38%, EER 1.90%, bestEER 1.76%
再往后的epoch性能也没有提升。

**Comment by TaoRuijie** [comment]
没有试过。。因为我一直只有一张卡 - -

**Comment by liuxuechaoliu** [comment]
我用4张显卡训练：80 epoch, LR 0.000090, LOSS 1.314495, ACC 71.51%, EER 2.91%, bestEER 2.85%。
但是当我再加载这个模型继续训练时，效果很差，就像没有训练过一样，我不知道为什么？大家能解答吗？
实际上，我用作者的预训练模型训练，效果也是很差。
translation：I train with 4 graphics cards：80 epoch, LR 0.000090, LOSS 1.314495, ACC 71.51%, EER 2.91%, bestEER 2.85%。
But when I reload this model to continue training, the effect is very poor, as if it has not been trained, I don't know why? Can you answer it?
In fact, I trained with the author's pre-trained model, and the effect is also very poor.

**Comment by liuxuechaoliu** [comment]
我用4张显卡训练80轮的结果：80 epoch, LR 0.000090, LOSS 1.314495, ACC 71.51%, EER 2.91%, bestEER 2.85%。
但是当我中断训练，之后再加载这个80轮模型继续训练时，效果很差，就像没有训练过一样，我不知道为什么？大家能解答吗？
![image](https://user-images.githubusercontent.com/92293853/205331867-6a92eba9-d8e9-4f6b-b5fa-ae8f197a50de.png)
