### ISSUE TITLE
ECAPA-TDNN

### ISSUE THREAD

**Issue by rosana-sc7** [TaoRuijie/ECAPA-TDNN#50]
Hi!

I'm having trouble understanding ECAPA-TDNN architecture. 

![image](https://user-images.githubusercontent.com/116825679/208719204-bef878bc-4b2e-42dc-9b99-01d128623e0c.png)

To be specific, I don't understand what does the elements in ECAPA-TDNN do (PreEmphasis,MelSpectrogram,FBankAug,conv1d,relu, batchNorm1d, bottleneck, Attention...) in the context of speaker verification?

What about classifier AAAsoftmax, optimizer Adam and scheduler stepLR?

Thanks for your attention and time!

**Comment by TaoRuijie** [comment]
Er sorry it looks too hard to answer your question.....Sorry
