### ISSUE TITLE
如何解决训练较慢

### ISSUE THREAD

**Issue by wcx881212** [TaoRuijie/ECAPA-TDNN#51]
学长您好 我照着您的代码跑实验时 训练较慢。感觉是CPU读入数据的时候花费了很长时间（设置读入线程为4时，每次四个batch训练完成后就会等半分钟秒左右。），请问有什么解决办法吗。
这是我的实验以及配置截图：
![截图20230307100011](https://user-images.githubusercontent.com/82487501/223300470-4f4730e9-d20d-4b4b-8d5e-5120e1b01d10.png)
![截图20230307100509](https://user-images.githubusercontent.com/82487501/223300803-f0a1490c-d496-4869-9bce-01e0c6ca927f.png)

**Comment by TbrooksT** [comment]
请看这个视频：

https://www.bilibili.com/video/BV1dF411g7t1/

**Comment by TaoRuijie** [comment]
请看这个视频https://www.bilibili.com/video/BV1dF411g7t1/

**Comment by aabbccn** [comment]
> 学长您好 我照着您的代码跑实验时 训练较慢。感觉是CPU读入数据的时候花费了很长时间（设置读入线程为4时，每次四个batch训练完成后就会等半分钟秒左右。），请问有什么解决办法吗。 这是我的实验以及配置截图： ![截图20230307100011](https://user-images.githubusercontent.com/82487501/223300470-4f4730e9-d20d-4b4b-8d5e-5120e1b01d10.png) ![截图20230307100509](https://user-images.githubusercontent.com/82487501/223300803-f0a1490c-d496-4869-9bce-01e0c6ca927f.png)

你好，请问现在解决模型收敛慢的问题了吗，是怎么解决的呢
