### ISSUE TITLE
about using pretrain model to continue training on the other data

### ISSUE THREAD

**Issue by phchtl** [TaoRuijie/ECAPA-TDNN#56]
i want to ask should i change the n_class（the number of speaker）， if i only change the n_class，it will go to error because of the difference of embedding size when loading the pretrain model.Thank you so much!

**Comment by TaoRuijie** [comment]
If you change the n_class, the classification layer is different. You should load the pretrain model without the classification layer only.

**Comment by freshpearYoon** [comment]
Hi, I am trying the same thing, and should I change the code so that it can load model without the classification layer? Because I think that is not implemented.
