### ISSUE TITLE
data augmentation

### ISSUE THREAD

**Issue by JINzezhong7** [TaoRuijie/ECAPA-TDNN#57]
I find in the system description， you say adding one music file and one noise file. but in code, it seems adding one music file and 3-8 speech file.

**Comment by TaoRuijie** [comment]
in here: https://github.com/TaoRuijie/ECAPA-TDNN/blob/main/dataLoader.py#L58

**Comment by JINzezhong7** [comment]
![image](https://user-images.githubusercontent.com/131787594/236731486-13dc6609-4aaa-42fa-a398-f309528cfdd8.png) but in this is music and noise file. the code is music and speech file

**Comment by TaoRuijie** [comment]
oh that is a mistake for description. I modfiy it now. thanks

While this part will not effect the result too much, I find augmentation without this type is ok

**Comment by JINzezhong7** [comment]
no thanks.  I have another question
![image](https://user-images.githubusercontent.com/131787594/237056815-d1c6826d-b1c7-45e7-bf85-1457f306fb98.png)
If you are like me when calculating the score, will the final EER be different?

**Comment by TaoRuijie** [comment]
Might be similar I guess

**Comment by TaoRuijie** [comment]
I cannot understand your question. If you mean the trick for cal EER, it only effect 5% (0.96 vs 1.01)
