### ISSUE TITLE
关于MSE可以提升结果

### ISSUE THREAD

**Issue by Dhu-alair** [TaoRuijie/ECAPA-TDNN#58]
学长你好！我在已经关闭的问题中注意到您在eval process中使用了MSE，从而导致结果会有大约0.05%的提升。我不是很理解MSE该怎么用到eval中，您可以解答一下吗？期待您的回复

**Comment by TaoRuijie** [comment]
你好。可以看这里：https://github.com/TaoRuijie/ECAPA-TDNN/issues/40
