### ISSUE TITLE
关于数据集prepare部分的问题

### ISSUE THREAD

**Issue by Evewillson** [TaoRuijie/ECAPA-TDNN#61]
我使用自己的用户名和密码执行命令“python ./dataprep.py --save_path data --download --user USERNAME --password PASSWORD”，但得到了下面的响应。而且我也尝试亲自打开网址，失败了

--2023-08-03 15:31:27--  http://cnode01.mm.kaist.ac.kr/voxceleb/vox1a/vox1_dev_wav_partaa
正在解析主机 cnode01.mm.kaist.ac.kr (cnode01.mm.kaist.ac.kr)... 143.248.230.30
正在连接 cnode01.mm.kaist.ac.kr (cnode01.mm.kaist.ac.kr)|143.248.230.30|:80... 已连接。
已发出 HTTP 请求，正在等待回应... 没有接收到数据。
重试中。

--2023-08-03 15:31:38--  (尝试次数： 2)  http://cnode01.mm.kaist.ac.kr/voxceleb/vox1a/vox1_dev_wav_partaa
正在连接 cnode01.mm.kaist.ac.kr (cnode01.mm.kaist.ac.kr)|143.248.230.30|:80... 已连接。
已发出 HTTP 请求，正在等待回应... 没有接收到数据。
重试中。

--2023-08-03 15:31:48--  (尝试次数： 3)  http://cnode01.mm.kaist.ac.kr/voxceleb/vox1a/vox1_dev_wav_partaa
正在连接 cnode01.mm.kaist.ac.kr (cnode01.mm.kaist.ac.kr)|143.248.230.30|:80... 已连接。
已发出 HTTP 请求，正在等待回应... 没有接收到数据。
重试中。

--2023-08-03 15:32:01--  (尝试次数： 4)  http://cnode01.mm.kaist.ac.kr/voxceleb/vox1a/vox1_dev_wav_partaa
正在连接 cnode01.mm.kaist.ac.kr (cnode01.mm.kaist.ac.kr)|143.248.230.30|:80... 已连接。
已发出 HTTP 请求，正在等待回应... 没有接收到数据。
重试中。

--2023-08-03 15:32:12--  (尝试次数： 5)  http://cnode01.mm.kaist.ac.kr/voxceleb/vox1a/vox1_dev_wav_partaa
正在连接 cnode01.mm.kaist.ac.kr (cnode01.mm.kaist.ac.kr)|143.248.230.30|:80... 已连接。
已发出 HTTP 请求，正在等待回应... 没有接收到数据。
重试中。

--2023-08-03 15:32:23--  (尝试次数： 6)  http://cnode01.mm.kaist.ac.kr/voxceleb/vox1a/vox1_dev_wav_partaa
正在连接 cnode01.mm.kaist.ac.kr (cnode01.mm.kaist.ac.kr)|143.248.230.30|:80... 已连接。
已发出 HTTP 请求，正在等待回应... 没有接收到数据。
重试中。

--2023-08-03 15:32:35--  (尝试次数： 7)  http://cnode01.mm.kaist.ac.kr/voxceleb/vox1a/vox1_dev_wav_partaa
正在连接 cnode01.mm.kaist.ac.kr (cnode01.mm.kaist.ac.kr)|143.248.230.30|:80... 已连接。
已发出 HTTP 请求，正在等待回应... 没有接收到数据。
重试中。

--2023-08-03 15:32:46--  (尝试次数： 8)  http://cnode01.mm.kaist.ac.kr/voxceleb/vox1a/vox1_dev_wav_partaa
正在连接 cnode01.mm.kaist.ac.kr (cnode01.mm.kaist.ac.kr)|143.248.230.30|:80... 已连接。
已发出 HTTP 请求，正在等待回应... 没有接收到数据。
重试中。

--2023-08-03 15:32:59--  (尝试次数： 9)  http://cnode01.mm.kaist.ac.kr/voxceleb/vox1a/vox1_dev_wav_partaa
正在连接 cnode01.mm.kaist.ac.kr (cnode01.mm.kaist.ac.kr)|143.248.230.30|:80... 已连接。
已发出 HTTP 请求，正在等待回应... 没有接收到数据。
重试中。

--2023-08-03 15:33:13--  (尝试次数：10)  http://cnode01.mm.kaist.ac.kr/voxceleb/vox1a/vox1_dev_wav_partaa
正在连接 cnode01.mm.kaist.ac.kr (cnode01.mm.kaist.ac.kr)|143.248.230.30|:80... 已连接。
已发出 HTTP 请求，正在等待回应... 没有接收到数据。
重试中。

--2023-08-03 15:33:28--  (尝试次数：11)  http://cnode01.mm.kaist.ac.kr/voxceleb/vox1a/vox1_dev_wav_partaa
正在连接 cnode01.mm.kaist.ac.kr (cnode01.mm.kaist.ac.kr)|143.248.230.30|:80... 已连接。
已发出 HTTP 请求，正在等待回应... 没有接收到数据。
重试中。

--2023-08-03 15:33:43--  (尝试次数：12)  http://cnode01.mm.kaist.ac.kr/voxceleb/vox1a/vox1_dev_wav_partaa
正在连接 cnode01.mm.kaist.ac.kr (cnode01.mm.kaist.ac.kr)|143.248.230.30|:80... 已连接。
已发出 HTTP 请求，正在等待回应... 没有接收到数据。
重试中。

**Comment by TaoRuijie** [comment]
这个好像是链接地址有问题 不太清楚啊这个数据集我也是用别人的 不好意思啊
