### ISSUE TITLE
dataLoader

### ISSUE THREAD

**Issue by lanjinglingbetty** [TaoRuijie/ECAPA-TDNN#63]
Traceback (most recent call last):Training 40.91%,Loss:9.28958,ACC:16.89%
File"/home/ECAPA-TDNN-main/dataLoader.py",line 113,in add_noise
return noise+audio
ValueError: operands could not be broadcast together with shapes(1,32240) (1,32240,2)
请问该怎么改呀
![新bug](https://github.com/TaoRuijie/ECAPA-TDNN/assets/46836558/67863804-6ebd-46d0-98fc-30045a76b6f3)

**Comment by TaoRuijie** [comment]
你的噪声数据不对 没有处理好

**Comment by lanjinglingbetty** [comment]
是噪声数据集不对吗

**Comment by TaoRuijie** [comment]
对，检查一下为什么shape 里有2

**Comment by aabbccn** [comment]
> 
你好，请问你解决shape里有2的问题了吗，我现在噪音shape为(1, 32240, 8)，不知道该怎么解决8

**Comment by aabbccn** [comment]
> 是噪声数据集不对吗

你好，我现在也遇到了同样的问题，我看好像是因为噪声数据集是二维数据，请问你是经过降维解决的吗，是怎么降维的呢

**Comment by lanjinglingbetty** [comment]
> > 是噪声数据集不对吗
> 
> 你好，我现在也遇到了同样的问题，我看好像是因为噪声数据集是二维数据，请问你是经过降维解决的吗，是怎么降维的呢

不好意思，我print了一下dataloader，发现是我的train数据集存在问题，将有问题的数据替换掉之后就好了

**Comment by aabbccn** [comment]
> > > 是噪声数据集不对吗
> > 
> > 
> > 你好，我现在也遇到了同样的问题，我看好像是因为噪声数据集是二维数据，请问你是经过降维解决的吗，是怎么降维的呢
> 
> 不好意思，我print了一下dataloader，发现是我的train数据集存在问题，将有问题的数据替换掉之后就好了
好的，非常感谢，那请问正常情况下经过处理的audio和rirs的shape都是（1，32240）对吧

**Comment by aabbccn** [comment]
> > > 是噪声数据集不对吗
> > 
> > 
> > 你好，我现在也遇到了同样的问题，我看好像是因为噪声数据集是二维数据，请问你是经过降维解决的吗，是怎么降维的呢
> 
> 不好意思，我print了一下dataloader，发现是我的train数据集存在问题，将有问题的数据替换掉之后就好了

不知道你是否介意展开说说这个报错的原因吗，另外请问你的train数据集和rir数据集都是一维数据吗，十分感谢！

**Comment by aabbccn** [comment]
> > > 是噪声数据集不对吗
> > 
> > 
> > 你好，我现在也遇到了同样的问题，我看好像是因为噪声数据集是二维数据，请问你是经过降维解决的吗，是怎么降维的呢
> 
> 不好意思，我打印了一下dataloader，发现是我的train数据集存在问题，将有问题的数据替换掉之后就好了

请问是因为你的train数据里有二维数据吗，另外可否分享一下rir数据集下载链接呢，因为我怀疑是我rir数据集里有二维数据导致的这个bug，十分感谢！

**Comment by lanjinglingbetty** [comment]
train就是voxceleb的数据集，我的数据集有问题是因为有一些数据在label里有但是实际没有
rir数据集下载链接：https://www.[openslr.org](https://www.openslr.org/28/)/28/

**Comment by aabbccn** [comment]
> train就是voxceleb的数据集，我的数据集有问题是因为有一些数据在label里有但是实际没有 rir数据集下载链接：[https://www.[openslr.org](https://www.openslr.org/28/)/28/](https://www.%5Bopenslr.org%5D(https://www.openslr.org/28/)/28/)
好的，感谢！
