### ISSUE TITLE
data08文件夹

### ISSUE THREAD

**Issue by wangsheng3** [TaoRuijie/ECAPA-TDNN#64]
请问作者可以提供一下data08文件夹下的数据集和txt文件嘛？

**Comment by TaoRuijie** [comment]
数据太大了而且我没有版权，抱歉啊

**Comment by wangsheng3** [comment]
default="/data08/VoxCeleb1/veri_test2.txt",              help='The path of the evaluation list, veri_test2.txt comes from https://www.robots.ox.ac.uk/~vgg/data/voxceleb/meta/veri_test2.txt'),这是您的代码，这个链接中的voxceleb1的test.txt文件中有的id号在我最近下载的新的voxceleb1数据集里已经没有了，这种文件怎么处理呢？

**Comment by TaoRuijie** [comment]
如果找不到 且数量不多 那就只能跳过该数据了...

**Comment by wangsheng3** [comment]
跳过该数据的意思是指这种文件里的没有的语音数据不用管它，还是需要将这些数据清除，比如id10270的音频数据都没有，但是测试文件里有他的数据，是将测试文件里的id10270的信息删除还是不用管它？

**Comment by TaoRuijie** [comment]
不是很清楚你的意思，建议还是找到完整的测试数据。Skip掉是实在没办法的措施，因为跳过后report的结果也和别人的情况不同了。
