### ISSUE TITLE
model. files

### ISSUE THREAD

**Issue by Time-slice** [TaoRuijie/ECAPA-TDNN#66]
What is the process of generating model1,2,3~n files, I have been running for 24 hours, only generated three model files, and I have not started training

**Comment by TaoRuijie** [comment]
What does your meaning for three model files, model_0001.model? ...0003.model?

check your gpu usage condition during training

**Comment by Time-slice** [comment]
> 三个模型文件 model_0001.model 的含义是什么？...0003.型号？
> Yes, model 0001.model，Is the process of generating training？It is very slow to generate them, about 10 hours to generate one, and the utilization rate of GPU is 0, what is the reason？
> 训练时检查你的GPU使用情况

**Comment by TaoRuijie** [comment]
1是第一个epoch后的model文件，2是第二个 以此类推

检查你的gpu使用率

详情可以看这个视频
https://www.bilibili.com/video/BV1dF411g7t1/?share_source=copy_web&vd_source=51a0a7cde6b6ec9e7d1c2cacdb0aaa9d

**Comment by Time-slice** [comment]
Thank you very much,your code and video have been very helpful to me


Soleil
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TaoRuijie/ECAPA-TDNN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月16日(星期一) 下午2:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TaoRuijie/ECAPA-TDNN] model. files (Issue #66)





 
1是第一个epoch后的model文件，2是第二个 以此类推
 
检查你的gpu使用率
 
详情可以看这个视频
 https://www.bilibili.com/video/BV1dF411g7t1/?share_source=copy_web&amp;vd_source=51a0a7cde6b6ec9e7d1c2cacdb0aaa9d

**Comment by Time-slice** [comment]
Hello, Mr. Black, I am a new researcher in the field of speaker recognition, and I have two questions to ask you: 

1. I noticed that some papers use 40 dimensions of Fbank feature, and some use 80 dimensions 

2.&nbsp;Speed Perturb&nbsp;for data&nbsp;augmentation



Do these two items have a big impact on EER? 

I would appreciate it if you could give me your answer !





&nbsp;

**Comment by TaoRuijie** [comment]
1. I noticed that some papers use 40 dimensions of Fbank feature, and some use 80 dimensions
 This effect a bit, not so huge.
2.&nbsp;Speed Perturb&nbsp;for data&nbsp;augmentation
 In VoxCeleb2, effect is limited, in CnCeleb, it can improve a lot.
