### ISSUE TITLE
想请教关于batchsize对结果的影响

### ISSUE THREAD

**Issue by wcqy-ye** [TaoRuijie/ECAPA-TDNN#70]
小黑up您好：
我之前在您的直播中提出过关于batchsize对eer影响的问题，我在我的4080 16g（我现在也在3090上尝试，但还没有出结果）上尝试复现您的结果，我的修改和结果如下：
1 我将batchsize从400改成200，其他参数未做修改。
![image](https://github.com/TaoRuijie/ECAPA-TDNN/assets/46421217/0db5b164-edbc-4d58-9ad3-63fd51a65fa2)
2 我将dataloader中的aug设置为0，也就是不使用加噪和混响
![image](https://github.com/TaoRuijie/ECAPA-TDNN/assets/46421217/820130fb-fc09-4158-ace2-5c65a4f959b2)
最后结果如图：
![image](https://github.com/TaoRuijie/ECAPA-TDNN/assets/46421217/ce747f01-46ee-40de-9a22-17f4064530af)
![Uploading image.png…]()
我认为这个结果已经远远高于您的0.96的结果，因此想请问您对此有没有见解和指教。
期待您的回复，感谢您做出的贡献（我是您b站铁粉嗷）

**Comment by TaoRuijie** [comment]
你好 这个和BATCHSIZE没有关系 因为你没有加噪 以我的经验没加噪模型收敛的很快 效果会差很多  详情可以看这个

https://www.bilibili.com/video/BV173411b7rq/

**Comment by wcqy-ye** [comment]
> 你好 这个和BATCHSIZE没有关系 因为你没有加噪 以我的经验没加噪模型收敛的很快 效果会差很多 详情可以看这个
> 
> https://www.bilibili.com/video/BV173411b7rq/

好的 谢谢您的回复，也就是说是因为我对aug的设置造成的这个结果是吗 那我重新再尝试一下取消对aug的设置进行复现，太感谢小黑up了

**Comment by TaoRuijie** [comment]
嗯是的 加噪对结果很重要 BATCHSIZE不是很大影响 没事

**Comment by wcqy-ye** [comment]
> 嗯是的 加噪对结果很重要 BATCHSIZE不是很大影响 没事

hh 好的 再次感谢，下次给您视频充电奥

**Comment by wcqy-ye** [comment]
> 嗯是的 加噪对结果很重要 BATCHSIZE不是很大影响 没事

不好意思，想再请教一下小黑up，我在加噪并且重新进行训练以及因为batchsize只有200达到收敛所需epoch增多所以增加总epoch数量之后结果如下：
![image](https://github.com/TaoRuijie/ECAPA-TDNN/assets/46421217/6a8bf1cf-0165-41be-95c8-a92289b66818)
我想请教您觉得1.03算是一个合理的结果吗
以及我在进行修改模型本身进行训练，这次训练batchsize只有100
![image](https://github.com/TaoRuijie/ECAPA-TDNN/assets/46421217/629d95c3-86c4-4460-948d-0769a0ca8e36)
我想请教一下您，就是我感觉loss太高了，而且相比于您的模型loss掉的太慢了，感觉不知道是不是没收敛（但是好像eer也不掉了）还是应该尝试在更大显存gpu上进行训练结果可能会好点？

**Comment by TaoRuijie** [comment]
1.03是正常的 同样的模型多次训练都有大概0.05左右的上下浮动一般我这个代码

加噪之后训练的loss肯定会变大，因为识别变得困难了，但eer会变好，这个不用看trainingloss基本上

这个batchsize有一些影响但不大

**Comment by wcqy-ye** [comment]
> 1.03是正常的 同样的模型多次训练都有大概0.05左右的上下浮动一般我这个代码
> 
> 加噪之后训练的loss肯定会变大，因为识别变得困难了，但eer会变好，这个不用看trainingloss基本上
> 
> 这个batchsize有一些影响但不大

好的 谢谢小黑up，意思是我修改了模型之后loss比较高，eer一直不掉，增大epoch也没什么用的，只能想办法改进模型了吧 再次感谢小黑up 去给您充电了

**Comment by TaoRuijie** [comment]
可能是你该模型的原因吧 这些EPOCH loss下不去啥的应该都是模型。

感谢支持~

**Comment by wenpeiyu123** [comment]
up 你好！ 我使用你复现的代码，没有改动，在3090上跑，最好的结果是eer为1.08 请问这个结果是合理的吗？

**Comment by wcqy-ye** [comment]
> up 你好！ 我使用你复现的代码，没有改动，在3090上跑，最好的结果是eer为1.08 请问这个结果是合理的吗？

我自己尝试了几次最好是1.03，你可以多跑几次试试，每次结果不一样的，或者加大一下epoch数量试下

**Comment by TaoRuijie** [comment]
> > up 你好！ 我使用你复现的代码，没有改动，在3090上跑，最好的结果是eer为1.08 请问这个结果是合理的吗？
> 
> 我自己尝试了几次最好是1.03，你可以多跑几次试试，每次结果不一样的，或者加大一下epoch数量试下

我没有设置random seed 基本上每次会有一些波动，会有差一些，不过1.08好像有点差了，我后来跑过几来最差可能1.03-1.04，最好0.94

**Comment by wenpeiyu123** [comment]
> > > up 你好！ 我使用你复现的代码，没有改动，在3090上跑，最好的结果是eer为1.08 请问这个结果是合理的吗？
> > 
> > 
> > 我自己尝试了几次最好是1.03，你可以多跑几次试试，每次结果不一样的，或者加大一下epoch数量试下
> 
> 我没有设置random seed 基本上每次会有一些波动，会有差一些，不过1.08好像有点差了，我后来跑过几来最差可能1.03-1.04，最好0.94
 请问n_cpu数目会对结果造成影响吗 我增加了n_cpu的数量
