### ISSUE TITLE
关于vox2数据集大小

### ISSUE THREAD

**Issue by aabbccn** [TaoRuijie/ECAPA-TDNN#74]
请问vox2音频部分的训练集，将其格式转为.wav文件后，大小是253G吗？
因为这个有点太大了，所以我怀疑自己是不是操作失误了。

**Comment by TaoRuijie** [comment]
它就是这么大。。

**Comment by aabbccn** [comment]
> 它就是这么大。。

！好的。
小黑，快更新b站，等你更新ing

**Comment by aabbccn** [comment]
> 它就是这么大。。

那这个训练时大概会占用多少内存和显存呢，因为服务器是实验室共用的，我害怕这么大运行起来会影响其他同学

**Comment by TaoRuijie** [comment]
数据集的大小和内存显存没有关系的，只和每个batch的数据有关

**Comment by aabbccn** [comment]
> 数据集的大小和内存显存没有关系的，只和每个batch的数据有关

好的，那数据集大小只和硬盘存储有关系是吧
