### ISSUE TITLE
test performance

### ISSUE THREAD

**Issue by wwyl2000** [TaoRuijie/ECAPA-TDNN#75]
Hi,
Thanks for your great work!
How to test performance?

**Comment by TaoRuijie** [comment]
If your testing data is in the same domain of VoxCeleb1 or 2, you can use the same threshold. The threshold comes from ComputeErrorRates function. (can also come from ComputeMinDcf is you focus on mindcf)

If you are using other dataset, a developmenet set is required to decide this threshold.

**Comment by wwyl2000** [comment]
Thanks for your help!
