### ISSUE TITLE
Best EER and the channels used

### ISSUE THREAD

**Issue by wwyl2000** [TaoRuijie/ECAPA-TDNN#79]
Hi,
Thanks again for your work.
My best EER is only about 1.03%, and i need more epochs to get this.

Thanks,
Willy

**Comment by TaoRuijie** [comment]
I did not set the seed so the results might be changed. usually I can get around 1.00 EER. 

From my experiments I find the device difference can also lead to some slight difference. My best performance is 0.94, the worst is 1.03 (same to u)

1024 is a good choice, it can lead to the best performance.

**Comment by wwyl2000** [comment]
Thanks Ruijie!
